# Generated by Django 3.1 on 2021-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210118_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='std',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('College', 'College'), ('work', 'work')], max_length=7),
        ),
    ]
