# Generated by Django 3.1 on 2021-01-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210119_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='std',
            field=models.CharField(choices=[('1     ', '1    '), ('2   ', '2   '), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('College', 'College'), ('work', 'work')], max_length=25),
        ),
    ]
