# Generated by Django 3.1 on 2021-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210324_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='show_your_email_to_others',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(default='e8372d63-c78c-45e7-97e1-6c31d6e5ce35', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='showing_email',
            field=models.BooleanField(default=False, verbose_name='Show your Email to others:'),
        ),
    ]
