# Generated by Django 3.1 on 2021-01-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, upload_to='question/images')),
                ('image2', models.ImageField(blank=True, upload_to='question/images')),
                ('image3', models.ImageField(blank=True, upload_to='question/images')),
                ('image4', models.ImageField(blank=True, upload_to='question/images')),
                ('file', models.FileField(blank=True, upload_to='')),
                ('actual_question', models.TextField()),
            ],
        ),
    ]
