# Generated by Django 3.1 on 2021-01-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='actual_question',
            new_name='question',
        ),
    ]
