# Generated by Django 3.1 on 2021-01-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210118_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('history', 'history'), ('geography', 'geography'), ('democratic politics', 'democratic politics'), ('economics', 'economics'), ('english', 'english'), ('Computer science', 'Computer science'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi')], default='maths', max_length=100),
        ),
    ]
