# Generated by Django 3.1 on 2021-01-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image4',
        ),
    ]
