# Generated by Django 3.1 on 2021-01-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='username',
        ),
    ]
