# Generated by Django 3.1 on 2021-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20210120_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='question/images/', width_field=450),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='question/images/', width_field=450),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='question/images/', width_field=450),
        ),
    ]
