# Generated by Django 3.1 on 2021-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20210120_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='question/files/'),
        ),
    ]
