# Generated by Django 3.1 on 2021-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20210120_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('history', 'history'), ('geography', 'geography'), ('democratic politics', 'democratic politics'), ('economics', 'economics'), ('english', 'english'), ('Computer science', 'Computer science'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('General', 'General')], default='maths', help_text='Required', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Required', max_length=150),
        ),
    ]
