# Generated by Django 3.1 on 2021-01-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0013_auto_20210122_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='comment/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='comment/images/')),
                ('file', models.FileField(blank=True, upload_to='comment/files/')),
                ('comment', models.CharField(max_length=1000000)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
