# Generated by Django 3.1 on 2021-01-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='question_pk',
        ),
    ]
