# Generated by Django 3.1 on 2021-01-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20210122_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question_pk',
            new_name='related_question',
        ),
    ]
