# Generated by Django 3.1 on 2021-01-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20210122_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question'),
        ),
    ]
