# Generated by Django 3.1 on 2021-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20210122_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000000),
        ),
    ]
