# Generated by Django 3.1 on 2021-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0019_auto_20210124_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='like', to='users.userprofile'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
        migrations.AddField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, default=0, related_name='downvote', to='users.userprofile'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvote',
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, default=0, related_name='upvote', to='users.userprofile'),
        ),
    ]
