# Generated by Django 3.1 on 2021-01-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20210124_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
    ]
