# Generated by Django 3.1 on 2021-01-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0021_remove_question_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvote', to='users.userprofile'),
        ),
    ]
