# Generated by Django 3.1 on 2021-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0023_auto_20210126_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvoted_question', to='users.userprofile'),
        ),
    ]
