# Generated by Django 3.1 on 2021-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0024_auto_20210126_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_viewed',
            field=models.ManyToManyField(blank=True, related_name='viewd_question', to='users.userprofile'),
        ),
    ]
