# Generated by Django 3.1 on 2021-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0025_question_user_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='report',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='reported_users',
            field=models.ManyToManyField(blank=True, related_name='report_question', to='users.userprofile'),
        ),
    ]
