# Generated by Django 3.1 on 2021-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0026_auto_20210126_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote_comment',
            field=models.ManyToManyField(blank=True, related_name='downvote_comment', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_comment',
            field=models.ManyToManyField(blank=True, related_name='upvoted_comment', to='users.userprofile'),
        ),
    ]
