# Generated by Django 3.1 on 2021-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0027_auto_20210129_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
