# Generated by Django 3.1 on 2021-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0028_comment_comment_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
