# Generated by Django 3.1 on 2021-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0030_auto_20210201_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image1',
            field=models.ImageField(null=True, upload_to='comment/images/'),
        ),
    ]
