# Generated by Django 3.1 on 2021-02-01 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0032_auto_20210201_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=datetime.datetime(2021, 2, 1, 17, 8, 9, 728697, tzinfo=utc)),
        ),
    ]
