# Generated by Django 3.1 on 2021-02-01 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0033_auto_20210201_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2021, 2, 1, 17, 9, 41, 746945, tzinfo=utc)),
        ),
    ]
