# Generated by Django 3.1 on 2021-02-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0034_auto_20210201_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
