# Generated by Django 3.1 on 2021-02-01 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0035_auto_20210201_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 24, 41, 878004, tzinfo=utc), null=True),
        ),
    ]
