# Generated by Django 3.1 on 2021-02-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0036_auto_20210201_2254'),
    ]

    operations = [
    ]
