# Generated by Django 3.1 on 2021-02-01 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210122_1247'),
        ('question', '0036_auto_20210201_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmark_question',
            field=models.ManyToManyField(blank=True, related_name='bookmark_question', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 17, 45, 50, 588289, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('history', 'history'), ('geography', 'geography'), ('democratic politics', 'democratic politics'), ('economics', 'economics'), ('english', 'english'), ('Computer science', 'Computer science'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('General', 'General')], default='maths', help_text='*required', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='*required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='*required', max_length=150),
        ),
    ]
