# Generated by Django 3.1 on 2021-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0039_auto_20210201_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(help_text='*required', max_length=150, null=True),
        ),
    ]
