# Generated by Django 3.1.7 on 2021-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0044_question_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_ip',
            field=models.TextField(default=None, null=True),
        ),
    ]
