# Generated by Django 3.1.7 on 2021-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0045_auto_20210225_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_ip',
            field=models.TextField(default=None),
        ),
    ]
