# Generated by Django 3.1 on 2021-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0046_auto_20210225_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_ip',
            field=models.TextField(default='first_user'),
        ),
    ]
