# Generated by Django 3.1 on 2021-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0047_auto_20210324_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000000, verbose_name='Answer:'),
        ),
    ]
