# Generated by Django 6.0.5 on 2026-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0048_auto_20210420_0030'),
        ('users', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmark_question',
            field=models.ManyToManyField(blank=True, related_name='bookmark_question', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('maths', 'maths'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('history', 'history'), ('geography', 'geography'), ('democratic politics', 'democratic politics'), ('economics', 'economics'), ('english', 'english'), ('Computer science', 'Computer science'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('General', 'General')], default='maths', help_text='*required', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='*required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='*required', max_length=150),
        ),
    ]
